version: v2
name: ShellCheck
slug: shellcheck
type: content
summary: A shell script static analysis tool
description: |
  <a href="https://github.com/koalaman/shellcheck">ShellCheck</a> helps you write better Shell scripts. It points out obvious and nuanced syntax
  issues that could cause your script to fail.
beta: false
subscription_level: 1
default_configuration:
  installation:
    repo_languages:
      - Shell
subscribed_events:
  - pull_request.opened
  - pull_request.reopened
  - pull_request.synchronize
  - check_run.rerequested
